version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: ebay-postgres
    environment:
      POSTGRES_USER: ebay_user
      POSTGRES_PASSWORD: ebay_password
      POSTGRES_DB: ebay_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
